import { MODEL_FIELDS } from "../models/modelFields";

const FIELDS = Object.freeze({
  getAllUsers: {
    userId: { value: "_id", label: "User ID" },
    email: { value: "email", label: "Email" },
    cid: { value: "ctrader_id", label: "CTrader ID" },
    mt5id: { value: "mt5_id", label: "MT5 ID" },
    mt4id: { value: "mt4_id", label: "MT4 ID" },
    phone: { value: "phone", label: "Phone" },
    firstName: { value: "first_name", label: "First Name" },
    lastName: { value: "last_name", label: "Last Name" },
    country: { value: "country", label: "Country" },
    city: { value: "city", label: "City" },
    terms: { value: "terms", label: "Terms" },
    lastLogin: { value: "last_login", label: "Last Login" },
    language: { value: "metadata.language", label: "Language" },
    deviceType: { value: "metadata.deviceType", label: "Device Type" },
    dob: { value: "dob", label: "Date of Birth" },
    salesAgentId: { value: "sales_agent", label: "Sales Agent ID" },
    hasDocuments: { value: "flags.hasDocuments", label: "Has Documents" },
    kycStatus: { value: "flags.kycStatus", label: "KYC Status" },
    createdAt: { value: "createdAt", label: "Created At" },
    updatedAt: { value: "updatedAt", label: "Updated At" },
    demoAccounts: { value: "accounts.demo", label: "Demo Accounts" },
    liveAccounts: { value: "accounts.live", label: "Live Accounts" },
    depositAmount: {
      value: "accounts.total_deposits_usd",
      label: "Deposit Amount USD",
    },
    withdrawAmount: {
      value: "accounts.total_withdrawals_usd",
      label: "Withdrawal Amount USD",
    },
  },
  getUserReuqests: {
    requestId: { value: "_id", label: "Request ID" },
    userId: { value: "user._id", label: "User ID" },
    cid: { value: "user.ctrader_id", label: "Ctrader ID" },
    firstName: { value: "user.first_name", label: "First Name" },
    lastName: { value: "user.last_name", label: "Last Name" },
    email: { value: "user.email", label: "Email" },
    status: { value: "status", label: "Status" },
    requestType: { value: "request_type", label: "Request Type" },
    createdAt: { value: "createdAt", label: "Created At" },
    updatedAt: { value: "updatedAt", label: "Updated At" },
    // Delete account request fields
    description: { value: "metadata.description", label: "Description" },
    accountId: { value: "metadata.account_id", label: "Account ID" },
    accountLoginId: {
      value: "metadata.account_login_id",
      label: "Account Login ID",
    },
    // Withdrawal request fields
    transactionId: {
      value: "metadata.transaction_id",
      label: "Transaction ID",
    },
    accountId: { value: "metadata.account_id", label: "Account ID" },
    amount: { value: "metadata.amount", label: "Amount" },
    currency: { value: "metadata.currency", label: "Currency" },
    type: { value: "metadata.type", label: "Type" },
    details: { value: "metadata.details", label: "Details" },
  },
  userTransactions: {
    userReadableId: { value: "user.readableId", label: "User ID" },
    transactionId: { value: "_id", label: "Transaction ID" },
    userId: { value: "user._id", label: "User ID" },
    firstName: { value: "user.first_name", label: "First Name" },
    lastName: { value: "user.last_name", label: "Last Name" },
    email: { value: "user.email", label: "Email" },
    cid: { value: "user.ctrader_id", label: "Ctrader ID" },
    accountId: { value: "userAccount._id", label: "User Account" },
    loginId: { value: "userAccount.login_id", label: "Login ID" },
    transactionType: { value: "transaction_type", label: "Transaction Type" },
    intent: { value: "intent", label: "Intent" },
    sessionStatus: { value: "session_status", label: "Session Status" },
    praxisTransactionType: {
      value: "praxis_transaction_type",
      label: "Praxis Transaction Type",
    },
    transactionStatus: {
      value: "transaction_status",
      label: "Transaction Status",
    },
    tid: { value: "tid", label: "TID" },
    praxisTransactionId: {
      value: "transaction_id",
      label: "Praxis Transaction Id",
    },
    currency: { value: "currency", label: "Currency" },
    amount: { value: "amount", label: "Amount" },
    conversionRate: { value: "conversion_rate", label: "Conversion Rate" },
    processedCurrency: {
      value: "processed_currency",
      label: "Processed Currency",
    },
    processedAmount: { value: "processed_amount", label: "Processed Amount" },
    processedUsdConversionRate: {
      value: "processed_usd_conversion_rate",
      label: "Processed USD Conversion Rate",
    },
    processedUsdAmount: {
      value: "processed_usd_amount",
      label: "Processed USD Amount",
    },
    fee: { value: "fee", label: "Fee" },
    paymentMethod: { value: "payment_method", label: "Payment Method" },
    paymentProcessor: {
      value: "payment_processor",
      label: "Payment Processor",
    },
    gateway: { value: "gateway", label: "Gateway" },
    var1: { value: "variable1", label: "Variable 1" },
    var2: { value: "variable2", label: "Variable 2" },
    variable3: { value: "variable3", label: "Variable 3" },
    notes: { value: "variable2", label: "Notes" },
    accountPlatform: {
      value: "userAccount.platform",
      label: "Account Platform",
    },
    other: { value: "card", label: "Other" },

    promoCode: { value: "variable3", label: "Promo Code" },
    createdAt: { value: "createdAt", label: "Created At" },
    updatedAt: { value: "updatedAt", label: "Updated At" },
    utm_campaign: { value: "user.utm_campaign", label: "UTM Campaign" },
    utm_source: { value: "user.utm_source", label: "UTM Source" },
    utm_medium: { value: "user.utm_medium", label: "UTM Medium" },
    utm_content: { value: "user.utm_content", label: "UTM Content" },
    utm_term: { value: "user.utm_term", label: "UTM Term" },
  },
});

export default FIELDS;
