export const MT4_DEMO_GROUPS = {
  TIOSV: {
    standard: {
      USD: "demoTM-STD_USD",
      EUR: "demoTM-STD_EUR",
      GBP: "demoTM-STD_GBP",
      // CAD: "demoTM-STD_CAD",
    },
  },
  TIOUK: {
    standard: {
      USD: "demoTIOUK-USD",
      EUR: "demoTIOUK-EUR",
      GBP: "demoTIOUK-GBP",
      CAD: "demoTIOUK-CAD",
    },
  },
};

export const MT4_LIVE_GROUPS = {
  TIOSV: {
    beataStandard: {
      USD: "TIO-USD_BMF_Std",
      EUR: "TIO-EUR_BMF_Std",
      CZK: "TIO-CZK_BMF_Std",
    },
    beataVip: {
      USD: "TIO-USD_BMF_V",
      EUR: "TIO-EUR_BMF_V",
      CZK: "TIO-CZK_BMF_V",
    },
    beataVipblack: {
      USD: "TIO-USD_BMF_VB",
      EUR: "TIO-EUR_BMF_VB",
      CZK: "TIO-CZK_BMF_VB",
    },
    interestFree: {
      USD: "TIO-USDint",
      EUR: "TIO-EURint",
      GBP: "TIO-GBPint",
      CAD: "TIO-CADint",
      AUD: "TIO-AUDint",
    },
    pamm: {
      USD: "TIO-USDPAMM",
      EUR: "TIO-EURPAMM",
      GBP: "TIO-GBPPAMM",
      CAD: "TIO-CADPAMM",
      USD6: "TIO-USDPAMM6",
    },
    socialTrading: {
      USD: "TIO-USDSocTr",
      EUR: "TIO-EURSocTr",
      GBP: "TIO-GBPSocTr",
      CAD: "TIO-CADSocTr",
      AUD: "TIO-AUDSocTr",
      ZAR: "TIO-ZARSocTr",
    },
    spreadOnly: {
      USD: "TIO-USD_sp",
      EUR: "TIO-EUR_sp",
      GBP: "TIO-GBP_sp",
      CAD: "TIO-CAD_sp",
      AUD: "TIO-AUD_sp",
      ZAR: "TIO-ZAR_sp",
      CZK: "TIO-CZK_sp",
    },
    spreadOnlyInterestFree: {
      USD: "TIO-USD_sp_int1",
      CAD: "TIO-CAD_sp_int1",
      GBP: "TIO-GBP_sp_int1",
      EUR: "TIO-EUR_sp_int1",
      AUD: "TIO-AUD_sp_int1",
    },
    standardIb: {
      USD: "TIO-USD8",
      EUR: "TIO-EUR8",
      GBP: "TIO-GBP8",
      CAD: "TIO-CAD8",
      AUD: "TIO-AUD8",
      ZAR: "TIO-ZAR8",
      CZK: "TIO-CZK8",
    },
    standard: {
      USD: "TIO-USD5",
      ZAR: "TIO-ZAR5",
      EUR: "TIO-EUR5",
      GBP: "TIO-GBP5",
      CAD: "TIO-CAD5",
      AUD: "TIO-AUD5",
      CZK: "TIO-CZK5",
    },
    vip: {
      USD: "TIO-USD2",
      EUR: "TIO-EUR2",
      GBP: "TIO-GBP2",
      CAD: "TIO-CAD2",
      AUD: "TIO-AUD2",
      CZK: "TIO-CZK2",
      ZAR: "TIO-ZAR2",
    },
    vipblack: {
      USD: "TIO-USDVip",
      EUR: "TIO-EURVip",
      GBP: "TIO-GBPVip",
      CAD: "TIO-CADVip",
      AUD: "TIO-AUDVip",
      CZK: "TIO-CZKVip",
      ZAR: "TIO-ZARVip",
    },
    nonStandard: [
      "TIO-USD10",
      "TIO-EUR10",
      "TIO-GBP10",
      "TIO-CAD10",
      "TIO-AUD10",
      "TIO-USD11",
      "TIO-EUR11",
      "TIO-GBP11",
      "TIO-CAD11",
      "TIO-AUD11",
      "TIO-USD16",
      "TIO-EUR16",
      "TIO-GBP16",
      "TIO-CAD16",
      "TIO-AUD16",
      "TIO-USDmu5",
      "TIO-EURmu5",
      "TIO-USD_ALP_Std",
      "TIO-USD_ALP_V",
      "TIO-USD_ALP_VB",
      "TIO-USD_CPL_Std",
      "TIO-USD_CPL_V",
      "TIO-USD_CPL_VB",
      "TIO-USD_Brazil",
      "TIO-EUR_Brazil",
      "TIO-GBP_Brazil",
      "TIO-USD7",
      "TIO-EUR20",
      "TIO-PricingUK",
      "TIO-EUR8FXMU",
      "TIO-USD8FXMU",
      "TIO-USD8MFX",
      "TIO-EUR2_Net",
      "TIO-USDVip_6i",
      "TIO-USD_STD0com",
      "TIO-USDint_0com",
      "TIO-USD_sp_com",
      "TIO-USD_sp_int",
      "TIO-USDCh_sp",
      "TIO-USDVip_5",
      "TIO-USDVip_5int",
      "TIO-USDPAMM6int",
      "TIO-CADPAMM8",
      "TIO-USDPAMMint",
      "TIO-USD_Raw7",
      "TIO-EUR_Raw7",
      "TIO-Cover",
    ],
  },
  TIOUK: {
    standard: {
      USD: "TIOUK-USD8",
      EUR: "TIOUK-EUR8",
      GBP: "TIOUK-GBP8",
    },
    standardEcp: {
      USD: "TIOUK-USD8Pro",
      EUR: "TIOUK-EUR8Pro",
      GBP: "TIOUK-GBP8Pro",
    },
    vip: {
      USD: "TIOUK-USD2",
      EUR: "TIOUK-EUR2",
      GBP: "TIOUK-GBP2",
    },
    vipEcp: {
      USD: "TIOUK-USD2Pro",
      EUR: "TIOUK-EUR2Pro",
      GBP: "TIOUK-GBP2Pro",
    },
    vipblack: {
      USD: "TIOUK-USDVip",
      EUR: "TIOUK-EURVip",
      GBP: "TIOUK-GBPVip",
    },
    vipblackEcp: {
      USD: "TIOUK-USDVipPro",
      EUR: "TIOUK-EURVipPro",
      GBP: "TIOUK-GBPVipPro",
    },
    nonStandardGroups: [
      "TIOUK-EURInsti",
      "TIOUK-EUR172Pro",
      "TIOUK-EUR_ITA_V",
      "TIOUK-EUR_ITA_2",
      "TIOUK-EUR_ITA_8",
      "TIOUK-USD-ITA_8",
      "TIOUK-USD-ITA_2",
      "TIOUK-USD-ITA_V",
      "TIOUK-USDRaw",
      "TIOUK-EURRaw",
      "TIOUK-GBPRaw",
      "TIOUK-Cover",
    ],
  },
};

export const MT4_SWAP_FREE_LIVE_GROUPS = {
  TIOSV: {
    standard: {
      USD: "TIO-USD5int",
      EUR: "TIO-EUR5int",
      GBP: "TIO-GBP5int",
      CAD: "TIO-CAD5int",
      AUD: "TIO-AUD5int",
    },
    vip: {
      USD: "TIO-USD2int",
      EUR: "TIO-EUR2int",
      GBP: "TIO-GBP2int",
      CAD: "TIO-CAD2int",
      AUD: "TIO-AUD2int",
    },
    vipblack: {
      USD: "TIO-USDVipint",
      EUR: "TIO-EURVipint",
      GBP: "TIO-GBPVipint",
      CAD: "TIO-CADVipint",
      AUD: "TIO-AUDVipint",
    },
    spreadOnly: {
      USD: "TIO-USD_sp_int1",
      EUR: "TIO-EUR_sp_int1",
      GBP: "TIO-GBP_sp_int1",
      CAD: "TIO-CAD_sp_int1",
      AUD: "TIO-AUD_sp_int1",
    },
    standardIb: {
      USD: "TIO-USDint",
      EUR: "TIO-EURint",
      GBP: "TIO-GBPint",
      CAD: "TIO-CADint",
      AUD: "TIO-AUDint",
    },
  },
};
