export const MT5_LIVE_GROUPS = {
  standardIb: {
    /// With IB
    EUR: "stv\\EUR",
    GBP: "stv\\GBP",
    USD: "stv\\USD",
    CAD: "stv\\CAD",
    AUD: "stv\\AUD",
    CZK: "stv\\CZK",
    ZAR: "stv\\ZAR",
    TIO: "stv\\TIO",
    USDT: "stv\\USDT",
    BTC: "stv\\BTC",
    ETH: "stv\\ETH",
  },
  vip: {
    EUR: "stv\\EUR_2",
    GBP: "stv\\GBP_2",
    USD: "stv\\USD_2",
    CAD: "stv\\CAD_2",
    AUD: "stv\\AUD_2",
    CZK: "stv\\CZK_2",
    ZAR: "stv\\ZAR_2",
    TIO: "stv\\TIO_2",
    USDT: "stv\\USDT_2",
    BTC: "stv\\BTC_2",
    ETH: "stv\\ETH_2",
  },
  vipblack: {
    EUR: "stv\\EUR_Vip",
    GBP: "stv\\GBP_Vip",
    USD: "stv\\USD_Vip",
    CAD: "stv\\CAD_Vip",
    AUD: "stv\\AUD_Vip",
    CZK: "stv\\CZK_Vip",
    ZAR: "stv\\ZAR_Vip",
    TIO: "stv\\TIO_Vip",
    USDT: "stv\\USDT_Vip",
    BTC: "stv\\BTC_Vip",
    ETH: "stv\\ETH_Vip",
  },
  standard: {
    // without IB
    EUR: "stv\\EUR_5",
    GBP: "stv\\GBP_5",
    USD: "stv\\USD_5",
    CAD: "stv\\CAD_5",
    AUD: "stv\\AUD_5",
    CZK: "stv\\CZK_5",
    ZAR: "stv\\ZAR_5",
    TIO: "stv\\TIO_5",
    USDT: "stv\\USDT_5",
    BTC: "stv\\BTC_5",
    ETH: "stv\\ETH_5",
  },
  vipblackClose: {
    // vipblack with close only
    // no CZK and ZAR
    EUR: "stv\\EUR_Vipc",
    GBP: "stv\\GBP_Vipc",
    USD: "stv\\USD_Vipc",
    CAD: "stv\\CAD_Vipc",
    AUD: "stv\\AUD_Vipc",
    TIO: "stv\\TIO_Vipc",
    USDT: "stv\\USDT_Vipc",
    BTC: "stv\\BTC_Vipc",
    ETH: "stv\\ETH_Vipc",
  },
  standard10Commission: {
    // standard with 10 dollar commission
    USD: "stv\\USD10",
    EUR: "stv\\EUR10",
    GBP: "stv\\GBP10",
    CAD: "stv\\CAD10",
    AUD: "stv\\AUD10",
    BTC: "stv\\BTC10",
    ETH: "stv\\ETH10",
    TIO: "stv\\TIO10",
  },
  standard11Commission6Indices: {
    // standard with 11 dollar commission on $6 indices
    USD: "stv\\USD11",
    EUR: "stv\\EUR11",
    GBP: "stv\\GBP11",
    CAD: "stv\\CAD11",
    AUD: "stv\\AUD11",
    BTC: "stv\\BTC16",
    ETH: "stv\\ETH16",
    TIO: "stv\\TIO16",
    USD: "stv\\USD16",
    EUR: "stv\\EUR16",
    GBP: "stv\\GBP16",
    CAD: "stv\\CAD16",
    AUD: "stv\\AUD16",
    BTC: "stv\\BTC11",
    ETH: "stv\\ETH11",
    TIO: "stv\\TIO11",
  },
  spreadOnly: {
    // spread only
    USD: "stv\\USD_sp",
    EUR: "stv\\EUR_sp",
    GBP: "stv\\GBP_sp",
    CAD: "stv\\CAD_sp",
    AUD: "stv\\AUD_sp",
    ZAR: "stv\\ZAR_sp",
    CZK: "stv\\CZK_sp",
    UST: "stv\\USDT_sp",
    BTC: "stv\\BTC_sp",
    ETH: "stv\\ETH_sp",
    TIO: "stv\\TIO_sp",
  },
  copyTrading: {
    USD: "stv\\USD_SocTr",
    EUR: "stv\\EUR_SocTr",
    GBP: "stv\\GBP_SocTr",
    CAD: "stv\\CAD_SocTr",
    AUD: "stv\\AUD_SocTr",
    ZAR: "stv\\ZAR_SocTr",
    UST: "stv\\USDT_SocTr",
    BTC: "stv\\BTC_SocTr",
    ETH: "stv\\ETH_SocTr",
    TIO: "stv\\TIO_SocTr",
  },
};

export const MT5_LIVE_SWAP_FREE_GROUPS = {
  standard: {
    USD: "stv\\USD_5_int",
    EUR: "stv\\EUR_5_int",
    GBP: "stv\\GBP_5_int",
    CAD: "stv\\CAD_5_int",
    AUD: "stv\\AUD_5_int",
    BTC: "stv\\BTC_5_int",
    ETH: "stv\\ETH_5_int",
    USDT: "stv\\USDT_5_int",
  },
  vip: {
    USD: "stv\\USD_2_int",
    EUR: "stv\\EUR_2_int",
    GBP: "stv\\GBP_2_int",
    CAD: "stv\\CAD_2_int",
    AUD: "stv\\AUD_2_int",
    BTC: "stv\\BTC_2_int",
    ETH: "stv\\ETH_2_int",
    USDT: "stv\\USDT_2_int",
  },
  vipblack: {
    USD: "stv\\USD_Vip_int",
    EUR: "stv\\EUR_Vip_int",
    GBP: "stv\\GBP_Vip_int",
    CAD: "stv\\CAD_Vip_int",
    AUD: "stv\\AUD_Vip_int",
    BTC: "stv\\BTC_Vip_int",
    ETH: "stv\\ETH_Vip_int",
    USDT: "stv\\USDT_Vip_int",
  },
  spreadOnly: {
    USD: "stv\\USD_sp_int",
    EUR: "stv\\EUR_sp_int",
    GBP: "stv\\GBP_sp_int",
    CAD: "stv\\CAD_sp_int",
    AUD: "stv\\AUD_sp_int",
    BTC: "stv\\BTC_sp_int",
    ETH: "stv\\ETH_sp_int",
    USDT: "stv\\USDT_sp_int",
  },
  standardIb: {
    USD: "stv\\USD_int",
    EUR: "stv\\EUR_int",
    GBP: "stv\\GBP_int",
    CAD: "stv\\CAD_int",
    AUD: "stv\\AUD_int",
    BTC: "stv\\BTC_int",
    ETH: "stv\\ETH_int",
    USDT: "stv\\USDT_int",
  },
};

export const MT5_DEMO_GROUPS = {
  standard: {
    USD: "demo\\forex-usd",
    EUR: "demo\\forex-eur",
    GBP: "demo\\forex-gbp",
    TIO: "demo\\forex-tio",
    BTC: "demo\\forex-btc",
    ETH: "demo\\forex-eth",
  },
};

export const ORDER_TRADE_ACTIVATION_FLAGS = {
  ACTIV_FLAGS_NONE: 0,
  ACTIV_FLAGS_NO_LIMIT: 1,
  ACTIV_FLAGS_NO_STOP: 2,
  ACTIV_FLAGS_NO_SLIMIT: 4,
  ACTIV_FLAGS_NO_SL: 8,
  ACTIV_FLAGS_NO_TP: 16,
  ACTIV_FLAGS_NO_SO: 32,
  ACTIV_FLAGS_NO_EXPIRATION: 64,
  ACTIV_FLAGS_ALL: 127,
};

export const ORDER_TYPE = {
  OP_BUY: 0,
  OP_FIRST: 0,
  OP_SELL: 1,
  OP_BUY_LIMIT: 2,
  OP_SELL_LIMIT: 3,
  OP_BUY_STOP: 4,
  OP_SELL_STOP: 5,
  OP_BUY_STOP_LIMIT: 6,
  OP_SELL_STOP_LIMIT: 7,
  OP_CLOSE_BY: 8,
  OP_LAST: 8,
};

export const ORDER_FILLING = {
  ORDER_FILL_FOK: 0,
  ORDER_FILL_FIRST: 0,
  ORDER_FILL_IOC: 1,
  ORDER_FILL_RETURN: 2,
  ORDER_FILL_LAST: 2,
};

export const ORDER_TIME = {
  ORDER_TIME_GTC: 0,
  ORDER_TIME_FIRST: 0,
  ORDER_TIME_DAY: 1,
  ORDER_TIME_SPECIFIED: 2,
  ORDER_TIME_SPECIFIED_DAY: 3,
  ORDER_TIME_LAST: 3,
};

export const ORDER_STATE = {
  ORDER_STATE_STARTED: 0,
  ORDER_STATE_FIRST: 0,
  ORDER_STATE_PLACED: 1,
  ORDER_STATE_CANCELED: 2,
  ORDER_STATE_PARTIAL: 3,
  ORDER_STATE_FILLED: 4,
  ORDER_STATE_REJECTED: 5,
  ORDER_STATE_EXPIRED: 6,
  ORDER_STATE_REQUEST_ADD: 7,
  ORDER_STATE_REQUEST_MODIFY: 8,
  ORDER_STATE_REQUEST_CANCEL: 9,
  ORDER_STATE_LAST: 9,
};

export const ORDER_ACTIVATION = {
  ACTIVATION_NONE: 0,
  ACTIVATION_FIRST: 0,
  ACTIVATION_PENDING: 1,
  ACTIVATION_STOPLIMIT: 2,
  ACTIVATION_EXPIRATION: 3,
  ACTIVATION_STOPOUT: 4,
  ACTIVATION_LAST: 4,
};

export const ORDER_REASON = {
  ORDER_REASON_CLIENT: 0,
  ORDER_REASON_FIRST: 0,
  ORDER_REASON_EXPERT: 1,
  ORDER_REASON_DEALER: 2,
  ORDER_REASON_SL: 3,
  ORDER_REASON_TP: 4,
  ORDER_REASON_SO: 5,
  ORDER_REASON_ROLLOVER: 6,
  ORDER_REASON_EXTERNAL_CLIENT: 7,
  ORDER_REASON_VMARGIN: 8,
  ORDER_REASON_GATEWAY: 9,
  ORDER_REASON_SIGNAL: 10,
  ORDER_REASON_SETTLEMENT: 11,
  ORDER_REASON_TRANSFER: 12,
  ORDER_REASON_SYNC: 13,
  ORDER_REASON_EXTERNAL_SERVICE: 14,
  ORDER_REASON_MIGRATION: 15,
  ORDER_REASON_MOBILE: 16,
  ORDER_REASON_WEB: 17,
  ORDER_REASON_SPLIT: 18,
  ORDER_REASON_LAST: 18,
};

export const ORDER_TRADE_MODIFY_FLAGS = {
  MODIFY_FLAGS_NONE: 0,
  MODIFY_FLAGS_ADMIN: 1,
  MODIFY_FLAGS_MANAGER: 2,
  MODIFY_FLAGS_POSITION: 4,
  MODIFY_FLAGS_RESTORE: 8,
  MODIFY_FLAGS_API_ADMIN: 16,
  MODIFY_FLAGS_API_MANAGER: 32,
  MODIFY_FLAGS_API_SERVER: 64,
  MODIFY_FLAGS_API_GATEWAY: 128,
  MODIFY_FLAGS_ALL: 255,
};

export const DEAL_REASON = {
  DEAL_REASON_CLIENT: 0,
  DEAL_REASON_FIRST: 0,
  DEAL_REASON_EXPERT: 1,
  DEAL_REASON_DEALER: 2,
  DEAL_REASON_SL: 3,
  DEAL_REASON_TP: 4,
  DEAL_REASON_SO: 5,
  DEAL_REASON_ROLLOVER: 6,
  DEAL_REASON_EXTERNAL_CLIENT: 7,
  DEAL_REASON_VMARGIN: 8,
  DEAL_REASON_GATEWAY: 9,
  DEAL_REASON_SIGNAL: 10,
  DEAL_REASON_SETTLEMENT: 11,
  DEAL_REASON_TRANSFER: 12,
  DEAL_REASON_SYNC: 13,
  DEAL_REASON_EXTERNAL_SERVICE: 14,
  DEAL_REASON_MIGRATION: 15,
  DEAL_REASON_MOBILE: 16,
  DEAL_REASON_WEB: 17,
  DEAL_REASON_SPLIT: 18,
  DEAL_REASON_LAST: 18,
};

export const DEAL_ACTION = {
  DEAL_BUY: 0,
  DEAL_FIRST: 0,
  DEAL_SELL: 1,
  DEAL_BALANCE: 2,
  DEAL_CREDIT: 3,
  DEAL_CHARGE: 4,
  DEAL_CORRECTION: 5,
  DEAL_BONUS: 6,
  DEAL_COMMISSION: 7,
  DEAL_COMMISSION_DAILY: 8,
  DEAL_COMMISSION_MONTHLY: 9,
  DEAL_AGENT_DAILY: 10,
  DEAL_AGENT_MONTHLY: 11,
  DEAL_INTERESTRATE: 12,
  DEAL_BUY_CANCELED: 13,
  DEAL_SELL_CANCELED: 14,
  DEAL_DIVIDEND: 15,
  DEAL_DIVIDEND_FRANKED: 16,
  DEAL_TAX: 17,
  DEAL_AGENT: 18,
  DEAL_SO_COMPENSATION: 19,
  DEAL_SO_COMPENSATION_CREDIT: 20,
  DEAL_LAST: 20,
};

export const DEAL_ENTRY_FLAG = {
  ENTRY_IN: 0,
  ENTRY_FIRST: 0,
  ENTRY_OUT: 1,
  ENTRY_INOUT: 2,
  ENTRY_OUT_BY: 3,
  ENTRY_LAST: 3,
};

export const DEAL_TRADE_MODIFY_FLAGS = {
  MODIFY_FLAGS_NONE: 0,
  MODIFY_FLAGS_ADMIN: 1,
  MODIFY_FLAGS_MANAGER: 2,
  MODIFY_FLAGS_POSITION: 4,
  MODIFY_FLAGS_RESTORE: 8,
  MODIFY_FLAGS_API_ADMIN: 16,
  MODIFY_FLAGS_API_MANAGER: 32,
  MODIFY_FLAGS_API_SERVER: 64,
  MODIFY_FLAGS_API_GATEWAY: 128,
  MODIFY_FLAGS_ALL: 255,
};

export const POSITION_ACTION = {
  POSITION_BUY: 0,
  POSITION_FIRST: 0,
  POSITION_SELL: 1,
  POSITION_LAST: 1,
};

export const POSITION_ACTIVATION = {
  ACTIVATION_NONE: 0,
  ACTIVATION_FIRST: 0,
  ACTIVATION_SL: 1,
  ACTIVATION_TP: 2,
  ACTIVATION_STOPOUT: 3,
  ACTIVATION_LAST: 3,
};

export const POSITION_TRADE_ACTIVATION_FLAGS = {
  ACTIV_FLAGS_NONE: 0,
  ACTIV_FLAGS_NO_LIMIT: 1,
  ACTIV_FLAGS_NO_STOP: 2,
  ACTIV_FLAGS_NO_SLIMIT: 4,
  ACTIV_FLAGS_NO_SL: 8,
  ACTIV_FLAGS_NO_TP: 16,
  ACTIV_FLAGS_NO_SO: 32,
  ACTIV_FLAGS_NO_EXPIRATION: 64,
  ACTIV_FLAGS_ALL: 127,
};

export const POSITION_REASON = {
  POSITION_REASON_CLIENT: 0,
  POSITION_REASON_FIRST: 0,
  POSITION_REASON_EXPERT: 1,
  POSITION_REASON_DEALER: 2,
  POSITION_REASON_SL: 3,
  POSITION_REASON_TP: 4,
  POSITION_REASON_SO: 5,
  POSITION_REASON_ROLLOVER: 6,
  POSITION_REASON_EXTERNAL_CLIENT: 7,
  POSITION_REASON_VMARGIN: 8,
  POSITION_REASON_GATEWAY: 9,
  POSITION_REASON_SIGNAL: 10,
  POSITION_REASON_SETTLEMENT: 11,
  POSITION_REASON_TRANSFER: 12,
  POSITION_REASON_SYNC: 13,
  POSITION_REASON_EXTERNAL_SERVICE: 14,
  POSITION_REASON_MIGRATION: 15,
  POSITION_REASON_MOBILE: 16,
  POSITION_REASON_WEB: 17,
  POSITION_REASON_SPLIT: 18,
  POSITION_REASON_LAST: 18,
};

export const POSITION_TRADE_MODIFY_FLAGS = {
  MODIFY_FLAGS_NONE: 0,
  MODIFY_FLAGS_ADMIN: 1,
  MODIFY_FLAGS_MANAGER: 2,
  MODIFY_FLAGS_POSITION: 4,
  MODIFY_FLAGS_RESTORE: 8,
  MODIFY_FLAGS_API_ADMIN: 16,
  MODIFY_FLAGS_API_MANAGER: 32,
  MODIFY_FLAGS_API_SERVER: 64,
  MODIFY_FLAGS_API_GATEWAY: 128,
  MODIFY_FLAGS_ALL: 255,
};
