export const PERMISSIONS = Object.freeze({
  USERS: {
    logs: "users.logs",
    get_user: "users.get_user",
    get_users: "users.get_users",
    update_user: "users.update_user",
    view_user_extra_details: "users.view_user_extra_details",
    change_sales_assignment: "users.change_sales_assignment",
    update_utms: "users.update_utms",
    view_followups: "users.view_followups",
    refund_transaction: "users.refund_transaction",
    suspend_user: "users.suspend_user",
  },
  ACCOUNTS: {
    get_accounts: "accounts.get_accounts",
    per_account_id: "accounts.per_account_id",
    update_account: "accounts.update_account",
    delete_account: "accounts.delete_account",
    balance_operation: "accounts.balance_operation",
    transfer_opration: "accounts.transfer_opration",
    view_trades: "accounts.view_trades",
  },
  DOCUMENTS: {
    view_documents: "documents.view_documents",
    view_document_per_id: "documents.view_document_per_id",
    view_user_documents: "documents.view_user_documents",
    per_document_id: "documents.per_document_id",
    update_document: "documents.update_document",
    delete_document: "documents.delete_document",
    upload_user_documents: "documents.upload_user_documents",
    force_change_kyc_status: "documents.force_change_kyc_status",
  },
  UTILS: {
    export: "utils.export",
  },
  REQUESTS: {
    view_requests: "requests.view_requests",
    view_pending_withdrawals: "requests.view_pending_withdrawals",
    view_pending_deposits: "requests.view_pending_deposits",
    delete_account: "requests.delete_account",
    withdraw_from_account_status: "requests.withdraw_from_account_status",
    withdraw_from_account: "requests.withdraw_from_account",
    crypto_deposit: "requests.crypto_deposit",
    transfer_funds_between_accounts: "requests.transfer_funds_between_accounts",
    change_account_leverage: "requests.change_account_leverage",
  },
  TRANSACTIONS: {
    view_transactions: "transactions.view_transactions",
    export_transactions: "transactions.export_transactions",
    edit_transaction_refund: "transactions.edit_transaction_refund",
  },
  NOTES: {
    view_notes: "notes.view_notes",
    create_note: "notes.create_note",
    update_note: "notes.update_note",
    delete_note: "notes.delete_note",
  },
  FINANCIAL_NOTES: {
    view_financial_notes: "financial_notes.view_financial_notes",
    create_financial_note: "financial_notes.create_financial_note",
    update_financial_note: "financial_notes.update_financial_note",
    delete_financial_note: "financial_notes.delete_financial_note",
  },
  RIBBONS: {
    view_ribbons: "ribbons.view_ribbons",
    update_ribbons: "ribbons.update_ribbons",
    create_ribbons: "ribbons.create_ribbons",
  },
  USER_SEGMENTS: {
    view_user_segments: "user_segments.view_user_segments",
    update_user_segments: "user_segments.update_user_segments",
    create_user_segments: "user_segments.create_user_segments",
    view_user_segment_results: "user_segments.view_user_segment_results",
    delete_user_segments: "user_segments.delete_user_segments",
  },
  TRADES: {
    view_positions: "trades.view_positions",
    view_orders: "trades.view_orders",
    view_deals: "trades.view_deals",
  },
  CRM_USERS: {
    get_crm_users: "crm_users.get_crm_users",
    create_crm_user: "crm_users.create_crm_user",
    update_crm_user: "crm_users.update_crm_user",
    delete_crm_user: "crm_users.delete_crm_user",
    add_crm_user_permissions: "crm_users.add_crm_user_permissions",
    remove_crm_user_permissions: "crm_users.remove_crm_user_permissions",
    add_crm_user_sales_countries: "crm_users.add_crm_user_sales_countries",
    remove_crm_user_sales_countries:
      "crm_users.remove_crm_user_sales_countries",
    update_crm_user_whitelist_countries:
      "crm_users.update_crm_user_whitelist_countries",
  },
  ADMINISTRATION: {
    user_logs: "administration.user_logs",
  },
  ROLES: {
    view_roles: "roles.view_roles",
    delete_role: "roles.delete_role",
    create_role: "roles.create_role",
    add_role_permissions: "roles.add_role_permissions",
    remove_role_permissions: "roles.remove_role_permissions",
  },
  DEMOGRAPHICS: {
    get_transactions_per_month: "demographics.get_transactions_per_month",
    get_users_per_country: "demographics.get_users_per_country",
    get_users_per_device: "demographics.get_users_per_device",
    get_users_per_timeframe: "demographics.get_users_per_timeframe",
  },
  SCHEDULED_FUNCTIONS: {
    view_functions: "scheduled_functions.view_functions",
    edit_functions: "scheduled_functions.edit_functions",
    forcerun_functions: "scheduled_functions.forcerun_functions",
  },
  REPORTS: {
    finances: "reports.finances",
    first_time_deposits: "reports.first_time_deposits",
    utm_reports: "reports.utm_reports",
    active_traders: "reports.active_traders",
    balance_report: "reports.balance_report",
  },
  INTERNAL: {
    server_status: "internal.server_status",
    daily_analysis_email: "internal.daily_analysis_email",
    openpayd_update_details: "internal.openpayd_update_details",
    openpayd_sweep: "internal.openpayd_sweep",
    translation_tool: "internal.translation_tool",
    ai_blogpost_generator: "internal.ai_blogpost_generator",
    ib_leads_upload: "internal.ib_leads_upload",
  },
});
